### ISSUE TITLE
SHOW SLAVE HOSTS is unreliable

### ISSUE THREAD

**Issue by jcross-linkup** [ashraf-s9s/mysqlchk#3]
I've found SHOW SLAVE HOSTS to be unreliable as MySQL will remove a slave from that output after a short while once the slave has disconnected.  If there are no slaves currently connected the output can be blank.  That causes mysqlchk to return a failed status even though the master is okay.

For my purposes, if the mysql host is not read only, it is a master.  I've submitted a pull request that accomplishes that in #2 .  However, I'm not sure if that will be sufficient for everyone else's use cases.

**Comment by ashraf-s9s** [comment]
Thanks @jcross-linkup . I admit that the checks do not cover some corner cases like yours. I've merged your PRs and closing this thread. Thank you!
